// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHd4MITxKwT_k5ggffVs1Uv4S74u_4Wfw',
    appId: '1:56956781467:web:3ef3749cf66dff0bb0573e',
    messagingSenderId: '56956781467',
    projectId: 'conwithfirebase-5e24f',
    authDomain: 'conwithfirebase-5e24f.firebaseapp.com',
    storageBucket: 'conwithfirebase-5e24f.appspot.com',
    measurementId: 'G-6FMY6780WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGd-woKQoitQt7Aa9m018XQizoFXdsjkk',
    appId: '1:56956781467:android:6b020bbad444ed3db0573e',
    messagingSenderId: '56956781467',
    projectId: 'conwithfirebase-5e24f',
    storageBucket: 'conwithfirebase-5e24f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFMXVDMy4XyMlpoQ5MWP34UMgCWajVEfw',
    appId: '1:56956781467:ios:809230a5c8efaa7ab0573e',
    messagingSenderId: '56956781467',
    projectId: 'conwithfirebase-5e24f',
    storageBucket: 'conwithfirebase-5e24f.appspot.com',
    iosBundleId: 'com.example.firebaseConnectivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFMXVDMy4XyMlpoQ5MWP34UMgCWajVEfw',
    appId: '1:56956781467:ios:15264adc1fa82e0bb0573e',
    messagingSenderId: '56956781467',
    projectId: 'conwithfirebase-5e24f',
    storageBucket: 'conwithfirebase-5e24f.appspot.com',
    iosBundleId: 'com.example.firebaseConnectivity.RunnerTests',
  );
}
